name: Github - Readme Cards

on:
  schedule:
    - cron: '0 5 * * *' # Daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage&show_icons=true&theme=transparent
          path: profile/github-stats.svg
          token: ${{ secrets.README_TOKEN }}
  
      - name: Generate Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=donut-vertical&theme=transparent
          path: profile/github-toplangs.svg
          token: ${{ secrets.README_TOKEN }}

      - name: Generate Streak Card
        uses: be-next/github-streak-stats-action@v1
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.README_TOKEN }}
          output-path: profile/github-streak.svg
          theme: default
          hide-border: false

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
